# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunny', '0002_auto_20170721_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, help_text='от -3 до 3', verbose_name='оценка')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='comm',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='value',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Тема занятия', max_length=400, verbose_name='Тема занятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='cash',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='cite',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='рейтинг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='visits',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='cite',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, verbose_name='домашнее задание'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(to='sunny.Student'),
        ),
        migrations.AddField(
            model_name='value',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunny.Lesson'),
        ),
        migrations.AddField(
            model_name='value',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunny.Student'),
        ),
    ]
