# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sunny', '0003_auto_20170830_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sunny.Teacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата занятия'),
        ),
    ]
